version: 0.2

phases:
  install:
    commands:
      - echo "Enabling Corepack and installing pnpm"
      - corepack enable
      - corepack prepare pnpm@8.15.4 --activate
      - pnpm install
  build:
    commands:
      - echo "Building the project with pnpm"
      - pnpm run build
  post_build:
    commands:
      - echo "Invalidating CloudFront cache"
      - aws cloudfront create-invalidation --distribution-id E25X0768LDBJW3 --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist
